#!/bin/bash

# Variables
KEY_NAME="bcitkey"
KEY_PATH="$HOME/.ssh/$KEY_NAME.pub"
REGION="us-west-2"

# Check if the public key file exists
if [ ! -f "$KEY_PATH" ]; then
	echo "Key file not found"
	exit 1
fi

echo "Exporting public key from $KEY_PATH to EC2..."
aws ec2 import-key-pair \
	--key-name "$KEY_NAME" \
	--public-key-material fileb://"$KEY_PATH" \
	--region "$REGION"

# Check exit code of the aws command (0 = exited successfully)
if [ $? -eq 0 ]; then
	echo "Public key $KEY_NAME successfully exported to EC2"
fi
